// PlaybarReducer
export const SONG_CHANGED = "SONG_CHANGED";
export const PREV_SONG = "PREV_SONG";
export const NEXT_SONG = "NEXT_SONG";
export const SET_IMAGE = "SET_IMAGE";
export const INCREMENT_TIME = "INCREMENT_TIME";
export const SONG_END = "SONG_END";
export const SONG_PAUSED = "SONG_PAUSED";
export const SONG_PLAYED = "SONG_PLAYED";
export const CLEAR_SONG = "CLEAR_SONG";
export const CHANGE_TIME = "CHANGE_TIME";
export const ADJUST_VOLUME = "ADJUST_VOLUME";

// PlaybarSongListReducer
export const CHANGE_LIST = "CHANGE_LIST";
export const TOGGLE_SHUFFLE = "TOGGLE_SHUFFLE";
export const TOGGLE_REPEAT = "TOGGLE_REPEAT";
export const REMOVE_CURR_SONG_FROM_TEMP = "REMOVE_CURR_SONG_FROM_TEMP";
export const RENEW_SONG_LIST = "RENEW_SONG_LIST";
export const ADD_SONG_TO_HISTORY = "ADD_SONG_TO_HISTORY";
export const CLEAR_SONG_HISTORY = "CLEAR_SONG_HISTORY";
export const INCREMENT_HISTORY_INDEX = "INCREMENT_HISTORY_INDEX";
export const DECREMENT_HISTORY_INDEX = "DECREMENT_HISTORY_INDEX";
export const RESET_HISTORY_INDEX = "RESET_HISTORY_INDEX";
export const SET_HISTORY_INDEX = "SET_HISTORY_INDEX";
export const SET_SEEK_ON = "SET_SEEK_ON";
export const SET_SEEK_OFF = "SET_SEEK_OFF";
export const IS_MOUSEDOWN = "IS_MOUSEDOWN";
export const IS_NOT_MOUSEDOWN = "IS_NOT_MOUSEDOWN";
export const IS_VOLUME_MOUSEDOWN = "IS_VOLUME_MOUSEDOWN";
export const IS_VOLUME_NOT_MOUSEDOWN = "IS_VOLUME_NOT_MOUSEDOWN";
export const VOLUME_MUTE = "VOLUME_MUTE";
export const VOLUME_UNMUTE = "VOLUME_UNMUTE";
